# Generated by Django 3.2.6 on 2021-08-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurso', models.PositiveSmallIntegerField(verbose_name='Concurso')),
                ('data', models.DateField(verbose_name='Data')),
                ('primeiro_numero', models.PositiveSmallIntegerField(verbose_name='Primeiro Número')),
                ('segundo_numero', models.PositiveSmallIntegerField(verbose_name='Segundo Número')),
                ('terceiro_numero', models.PositiveSmallIntegerField(verbose_name='Terceiro Número')),
                ('quarto_numero', models.PositiveSmallIntegerField(verbose_name='Quarto Número')),
                ('quinto_numero', models.PositiveSmallIntegerField(verbose_name='Quinto Número')),
                ('sexto_numero', models.PositiveSmallIntegerField(verbose_name='Sexto Número')),
                ('setimo_numero', models.PositiveSmallIntegerField(verbose_name='Sétimo Número')),
                ('oitavo_numero', models.PositiveSmallIntegerField(verbose_name='Oitávo Número')),
                ('nono_numero', models.PositiveSmallIntegerField(verbose_name='Nono Número')),
                ('decimo_numero', models.PositiveSmallIntegerField(verbose_name='Decimo Número')),
                ('decimo_primeiro_numero', models.PositiveSmallIntegerField(verbose_name='Décimo Primeiro Número')),
                ('decimo_segundo_numero', models.PositiveSmallIntegerField(verbose_name='Décimo Segundo Número')),
                ('decimo_terceiro_numero', models.PositiveSmallIntegerField(verbose_name='Décimo Terceiro Número')),
                ('decimo_quarto_numero', models.PositiveSmallIntegerField(verbose_name='Décimo Quarto Número')),
                ('decimo_quinto_numero', models.PositiveSmallIntegerField(verbose_name='Décimo Quinto Número')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'db_table': 'resultado',
            },
        ),
    ]
