# Generated by Django 3.2.6 on 2021-08-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=194, verbose_name='Nome completo do usuário'),
        ),
    ]
