# Generated by Django 3.2.6 on 2021-08-10 04:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+41524204242", max_length=128, region=None),
            preserve_default=False,
        ),
    ]
